Remove data variant and data singleton. Add logging for OppositeDirec…
RobotecAI/ad-rss-lib pull request #10
Opened 2023-02-15 14:02 UTC by lchojnack

Changes: 
- Remove data variant and data singleton
- Add logging for OppositeDirection situation.

#### Description

Fixes #  

#### Where has this been tested?

  * **Platform(s):** ...
  * **Library version:** ...

#### Possible Drawbacks

2023-02-15 14:50 UTC, adamkrawczyk requested changes

2023-02-15 14:50 UTC, adamkrawczyk commented on ad_rss/src/situation/RssStructuredSceneIntersectionChecker.cpp
> +  auto &data_intersection = extended_situation_data.situation_data.back().data_intersection_.value();
Maybe do some func which could also check the safety?

2023-02-17 08:41 UTC, lchojnack commented on ad_rss/src/situation/RssStructuredSceneIntersectionChecker.cpp
> +  // auto &data_intersection = extended_situation_data.situation_data.back().data_intersection_.value();
Remove commented code

2023-02-17 08:41 UTC, lchojnack commented on ad_rss/src/logging/ExtendedSituationData.cpp
> +SituationData & ExtendedSituationData::safeGetLastSituationDataElement(){
Lintting issue.  '{' In new line

2023-02-17 08:41 UTC, lchojnack commented on ad_rss/src/logging/ExtendedSituationData.cpp
> +  if (situation_data.empty()){
Lintting issue.  '{' In new line

2023-02-17 08:41 UTC, lchojnack commented on ad_rss/src/logging/ExtendedSituationData.cpp
> +  if (data_intersection_.has_value()){
Lintting issue.  '{' In new line

2023-02-17 08:41 UTC, lchojnack commented on ad_rss/src/logging/ExtendedSituationData.cpp
> +  else{
Lintting issue.  '{' In new line

2023-02-17 08:46 UTC, adamkrawczyk commented on ad_rss/src/logging/ExtendedSituationData.cpp
> +SituationData & ExtendedSituationData::safeGetLastSituationDataElement(){
I will format with next commit

2023-02-17 14:12 UTC, merged